## 🧬 Behavioral Analytics: The Modern Student Triad
### Exploring AI Dependency, Career Anxiety, and Student Burnout

### 🧠 Project Motivation
Most publicly available education datasets focus strictly on traditional performance metrics like grades, test scores, or attendance records. While useful, they completely miss the massive psychological shifts occurring in the generative AI era. 

This notebook explores the intersection of three highly correlated contemporary phenomena: **Generative AI Dependency**, **Acute Career Anxiety**, and **Chronic Student Burnout**. Rather than existing as isolated issues, these factors form a compounding psychological feedback loop that alters how students learn, cope, and view their professional futures.

### 🛠️ Dataset Design Philosophy
Unlike simplistic synthetic datasets with perfectly linear relationships, this dataset was intentionally engineered to include real-world dataset characteristics:
* **Overlapping Behaviors:** Students exhibiting high AI usage alongside high manual study efforts.
* **Contradictory Personas:** High-performing students tracking high burnout levels.
* **Controlled Missingness:** Simulating real-world survey drops or unrecorded tracking metrics.
* **Moderate Correlations:** Introducing realistic noise and variance to prevent trivial decision boundaries.

### Automated Data Ingestion
To ensure maximum reproducibility and maintain clean versioning, we pull the official dataset directly from Kaggle utilizing the `kagglehub` library. 

This automated process fetches the raw behavioral data tracking AI usage metrics, burnout indicators, and career anxiety scales directly into our environment.

* **Dataset Credit:** Sridip Basu via Kaggle (*AI Dependency, Career Anxiety, and Student Burnout Dataset*).

**Link:** https://www.kaggle.com/datasets/sridipbasu/ai-depndency-career-anxiety-and-student-burnout

### 📥 Loading the Dataset and Libraries

Before we start, we need to install the necessary Python libraries and **load the dataset**.

In [84]:
# Install the required libraries
%pip install pandas numpy matplotlib seaborn scikit-learn scikit-optimize jupyterlab nbconvert imblearn xgboost sweetviz joblib -q
%pip install ucimlrepo -q

# Install and update the watermark package to display environment and library version information
%pip install -q -U watermark

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [85]:
# ==========================================
# 1. DATA MANIPULATION & VISUALIZATION
# ==========================================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib
import sweetviz as sv
import os
import kagglehub
import logging
import warnings
from sweetviz import FeatureConfig

warnings.filterwarnings('ignore', category=UserWarning)
logging.getLogger("matplotlib.font_manager").setLevel(logging.ERROR)

# ==========================================
# 2. PREPROCESSING & PIPELINES
# ==========================================
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# ==========================================
# 3. MACHINE LEARNING MODELS
# ==========================================
from sklearn.dummy import DummyClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

# ==========================================
# 4. MODEL SELECTION & HYPERTUNING
# ==========================================
from sklearn.model_selection import (
    train_test_split,
    StratifiedKFold,
    cross_val_score,
    cross_val_predict,
    GridSearchCV,
)

# ==========================================
# 5. METRICS & EVALUATION
# ==========================================
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    ConfusionMatrixDisplay,
)
from sklearn.metrics import roc_curve, auc
from sklearn.metrics import precision_recall_curve, average_precision_score

In [86]:
# Load the watermark extension to log the environment state
%reload_ext watermark

# Display professional metadata tracking our data engineering stack
%watermark -a "Maykon - AI_Dependency" -d -u -v -p pandas,numpy,matplotlib,seaborn,scikit-learn,scikit-optimize,jupyterlab,nbconvert,imblearn,xgboost,sweetviz,joblib

Author: Maykon - AI_Dependency

Last updated: 2026-07-25

Python implementation: CPython
Python version       : 3.13.7
IPython version      : 9.13.0

pandas         : 3.0.3
numpy          : 2.4.5
matplotlib     : 3.10.9
seaborn        : 0.13.2
scikit-learn   : 1.8.0
scikit-optimize: 0.10.2
jupyterlab     : 4.6.2
nbconvert      : 7.17.1
imblearn       : 0.0
xgboost        : 3.3.0
sweetviz       : 2.3.3
joblib         : 1.5.3

In [87]:
# --- AUTOMATED KAGGLE INGESTION ---
# Download the latest version of the specific student behavioral dataset
path = kagglehub.dataset_download("sridipbasu/ai-depndency-career-anxiety-and-student-burnout")
print("🚀 Path to dataset files:", path)

🚀 Path to dataset files: C:\Users\LarTI\.cache\kagglehub\datasets\sridipbasu\ai-depndency-career-anxiety-and-student-burnout\versions\1

In [88]:
# --- LOCATING AND READING THE CSV ---
# List out all files inside the downloaded repository path to spot the target file
all_files = os.listdir(path)
print("📂 Files discovered in directory:", all_files)

# Filter out all CSV files dynamically
csv_files = [file for file in all_files if file.endswith('.csv')]

if len(csv_files) == 0:
    raise FileNotFoundError("❌ Critical Error: No CSV files found in the downloaded folder!")
else:
    # Grab the primary CSV file found
    csv_filename = csv_files[0]
    full_csv_path = os.path.join(path, csv_filename)
    print(f"🎯 Target CSV located: {csv_filename}")

📂 Files discovered in directory: ['ai_dependency_career_anxiety_students.csv', 'dataset_metadata.json', 'feature_dictionary.csv']
🎯 Target CSV located: ai_dependency_career_anxiety_students.csv

In [89]:
# Ingest the dataset into a pandas DataFrame
df = pd.read_csv(full_csv_path)
print(f"✅ Dataset successfully loaded! Named 'df', Shape: {df.shape[0]} rows, {df.shape[1]} columns.")

✅ Dataset successfully loaded! Named 'df', Shape: 15000 rows, 30 columns.

In [90]:
# Display the first 5 records to see our column properties and labels
df.head()

,student_id,age,gender,degree_type,stream,year_of_study,college_tier,urban_or_rural,daily_ai_tool_usage_hrs,primary_ai_tools_used,...,daily_study_hours,self_learning_hours_per_week,skill_development_courses_taken,social_media_hrs_per_day,sleep_hours,stress_level,burnout_score,motivation_score,seeks_career_counseling,overall_career_readiness_score
0,STU_00001,25,Male,B.Tech/B.E.,Engineering (Non-CS),3,Tier 3,Rural,0.3,Perplexity,...,3.5,8.7,2,1.5,8.5,1,3,6,0.0,9.09
1,STU_00002,20,Female,B.Tech/B.E.,Engineering (Non-CS),4,Tier 3,Urban,1.9,ChatGPT,...,2.4,8.2,3,4.2,8.3,4,5,3,0.0,6.03
2,STU_00003,25,Female,MBA,CS/IT,1,Tier 3,Urban,3.6,Gemini,...,2.3,16.4,1,2.3,7.0,5,9,3,1.0,6.68
3,STU_00004,23,Male,B.Tech/B.E.,CS/IT,1,Tier 1,Urban,4.1,GitHub Copilot,...,7.7,15.0,3,2.6,7.2,6,6,6,0.0,7.71
4,STU_00005,22,Female,MBA,CS/IT,1,Tier 1,Urban,3.4,ChatGPT,...,2.4,1.1,2,1.9,8.0,3,5,4,0.0,4.64

In [91]:
df.shape # (rows, columns)
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 15000
Number of columns: 30

In [92]:
df.sample(15) # Random 15 rows

,student_id,age,gender,degree_type,stream,year_of_study,college_tier,urban_or_rural,daily_ai_tool_usage_hrs,primary_ai_tools_used,...,daily_study_hours,self_learning_hours_per_week,skill_development_courses_taken,social_media_hrs_per_day,sleep_hours,stress_level,burnout_score,motivation_score,seeks_career_counseling,overall_career_readiness_score
10589,STU_10590,21,Female,B.Sc/B.A/B.Com,CS/IT,1,Tier 1,Urban,3.2,ChatGPT,...,5.3,13.2,2,2.4,7.7,5,6,5,0.0,6.13
7349,STU_07350,25,Female,B.Tech/B.E.,CS/IT,2,Tier 1,Urban,4.4,ChatGPT,...,6.5,22.0,0,0.3,5.3,5,4,6,0.0,8.08
9241,STU_09242,21,Male,B.Sc/B.A/B.Com,CS/IT,3,Tier 3,Urban,4.4,ChatGPT,...,0.1,11.6,2,0.5,8.2,3,6,4,0.0,6.76
4053,STU_04054,21,Female,B.Tech/B.E.,CS/IT,4,Tier 2,Urban,3.8,ChatGPT,...,4.7,5.4,4,4.1,5.0,6,8,4,1.0,8.10
11680,STU_11681,20,Female,B.Tech/B.E.,CS/IT,3,Tier 3,Rural,4.6,ChatGPT,...,0.3,9.9,0,6.4,7.3,4,9,1,0.0,6.14
12679,STU_12680,20,Male,B.Sc/B.A/B.Com,CS/IT,2,Tier 2,Rural,5.8,ChatGPT,...,1.6,12.2,0,5.4,5.9,10,10,2,1.0,4.92
9731,STU_09732,18,Female,B.Tech/B.E.,CS/IT,2,Tier 3,Urban,2.1,Claude,...,2.6,10.3,4,3.6,7.4,4,4,4,0.0,6.98
6172,STU_06173,22,Male,B.Tech/B.E.,Engineering (Non-CS),3,Tier 3,Urban,0.2,ChatGPT,...,0.0,NaN,3,2.5,7.8,5,5,4,0.0,5.81
5359,STU_05360,24,Female,M.Tech/M.Sc,Commerce/Management,1,Tier 3,Urban,0.0,NaN,...,2.5,5.2,3,5.3,NaN,5,5,7,0.0,6.11
2682,STU_02683,25,Male,B.Sc/B.A/B.Com,Engineering (Non-CS),3,Tier 1,Urban,2.0,Claude,...,2.2,10.3,3,2.2,7.0,5,3,4,1.0,7.11
11745,STU_11746,19,Male,B.Tech/B.E.,Commerce/Management,1,Tier 3,Urban,0.0,NaN,...,3.3,0.8,6,1.9,7.1,5,5,6,0.0,6.05
14393,STU_14394,22,Non-binary,M.Tech/M.Sc,Engineering (Non-CS),2,Tier 3,Rural,0.8,ChatGPT,...,1.9,6.3,0,4.9,6.9,6,4,4,0.0,7.03
6500,STU_06501,23,Male,B.Sc/B.A/B.Com,CS/IT,3,Tier 3,Urban,2.8,ChatGPT,...,3.7,14.7,1,0.0,7.7,7,8,6,1.0,7.04
4210,STU_04211,21,Female,B.Sc/B.A/B.Com,Commerce/Management,3,Tier 2,Urban,0.2,Claude,...,1.3,7.3,2,2.2,8.9,2,1,7,0.0,6.12
12273,STU_12274,20,Male,B.Tech/B.E.,CS/IT,1,Tier 2,Rural,7.4,GitHub Copilot,...,0.5,7.4,1,5.8,7.9,5,6,3,1.0,4.65

In [93]:
df.tail() #Displays the last 5 rows of the DataFrame df.

,student_id,age,gender,degree_type,stream,year_of_study,college_tier,urban_or_rural,daily_ai_tool_usage_hrs,primary_ai_tools_used,...,daily_study_hours,self_learning_hours_per_week,skill_development_courses_taken,social_media_hrs_per_day,sleep_hours,stress_level,burnout_score,motivation_score,seeks_career_counseling,overall_career_readiness_score
14995,STU_14996,21,Female,B.Sc/B.A/B.Com,CS/IT,1,Tier 3,Urban,2.8,ChatGPT,...,0.0,6.2,2,0.2,9.6,4,6,2,0.0,7.02
14996,STU_14997,22,Male,B.Tech/B.E.,Commerce/Management,4,Tier 1,Urban,3.6,ChatGPT,...,6.1,11.7,3,2.9,5.8,5,3,9,1.0,7.31
14997,STU_14998,22,Male,B.Tech/B.E.,CS/IT,2,Tier 1,Rural,1.7,Gemini,...,6.3,17.2,5,0.6,7.4,3,1,9,0.0,8.65
14998,STU_14999,22,Female,MBA,CS/IT,2,Tier 2,Urban,0.0,NaN,...,0.8,0.0,1,2.0,9.1,5,6,2,0.0,4.97
14999,STU_15000,23,Male,M.Tech/M.Sc,Engineering (Non-CS),2,Tier 3,Rural,2.1,ChatGPT,...,2.9,1.0,3,3.9,7.4,7,7,4,0.0,5.28

In [94]:
df.dtypes #Displays the data type of each column in the DataFrame.

student_id                             str
age                                  int64
gender                                 str
degree_type                            str
stream                                 str
year_of_study                        int64
college_tier                           str
urban_or_rural                         str
daily_ai_tool_usage_hrs            float64
primary_ai_tools_used                  str
uses_ai_for_assignments                str
ai_replaces_own_thinking_score       int64
ai_dependency_score                  int64
placement_anxiety_score              int64
fear_of_job_loss_to_ai               int64
career_clarity_score                 int64
internship_experience                int64
weekly_job_application_count         int64
resume_confidence_score              int64
interview_anxiety_score              int64
daily_study_hours                  float64
self_learning_hours_per_week       float64
skill_development_courses_taken      int64
social_media_hrs_per_day           float64
sleep_hours                        float64
stress_level                         int64
burnout_score                        int64
motivation_score                     int64
seeks_career_counseling            float64
overall_career_readiness_score     float64
dtype: object

In [95]:
df.columns #Returns a list (Index object) containing the names of all columns in the DataFrame.

Index(['student_id', 'age', 'gender', 'degree_type', 'stream', 'year_of_study',
       'college_tier', 'urban_or_rural', 'daily_ai_tool_usage_hrs',
       'primary_ai_tools_used', 'uses_ai_for_assignments',
       'ai_replaces_own_thinking_score', 'ai_dependency_score',
       'placement_anxiety_score', 'fear_of_job_loss_to_ai',
       'career_clarity_score', 'internship_experience',
       'weekly_job_application_count', 'resume_confidence_score',
       'interview_anxiety_score', 'daily_study_hours',
       'self_learning_hours_per_week', 'skill_development_courses_taken',
       'social_media_hrs_per_day', 'sleep_hours', 'stress_level',
       'burnout_score', 'motivation_score', 'seeks_career_counseling',
       'overall_career_readiness_score'],
      dtype='str')

### 🧹 Data Preprocessing & Hygiene
Now that the data is loaded, we begin our cleaning pipeline. 
Our tasks in this phase are:
1. **Find the missing data:** Using the command **df.isna().sum()** 
2. **Drop Identifiers:** Remove `student_id` since it has no predictive or statistical power.
3. **Handle Missing Data:** Clean the columns containing missing values ($NaN$) using imputation strategies:
   * **Categorical Imputation:** Fill high-missingness text columns like `primary_ai_tools_used` with a default placeholder (`'None'`).
   * **Numerical Imputation:** Fill missing numerical features with their **Median** values to keep our distributions stable and unaffected by outliers.

In [96]:
df.isna().sum() # Count missing values per column

student_id                            0
age                                   0
gender                                0
degree_type                           0
stream                                0
year_of_study                         0
college_tier                          0
urban_or_rural                        0
daily_ai_tool_usage_hrs               0
primary_ai_tools_used              3215
uses_ai_for_assignments               0
ai_replaces_own_thinking_score        0
ai_dependency_score                   0
placement_anxiety_score               0
fear_of_job_loss_to_ai                0
career_clarity_score                  0
internship_experience                 0
weekly_job_application_count          0
resume_confidence_score               0
interview_anxiety_score               0
daily_study_hours                     0
self_learning_hours_per_week        233
skill_development_courses_taken       0
social_media_hrs_per_day            210
sleep_hours                         203
stress_level                          0
burnout_score                         0
motivation_score                      0
seeks_career_counseling             220
overall_career_readiness_score        0
dtype: int64

In [97]:
df.describe(include='all').T #Generates a complete statistical summary of the DataFrame.

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
student_id,15000,15000,STU_00001,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
age,15000.0,NaN,NaN,NaN,21.384533,2.005626,18.0,20.0,21.0,22.0,28.0
gender,15000,3,Male,7840,NaN,NaN,NaN,NaN,NaN,NaN,NaN
degree_type,15000,4,B.Tech/B.E.,6700,NaN,NaN,NaN,NaN,NaN,NaN,NaN
stream,15000,4,CS/IT,6091,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year_of_study,15000.0,NaN,NaN,NaN,2.100067,0.98765,1.0,1.0,2.0,3.0,4.0
college_tier,15000,3,Tier 3,7475,NaN,NaN,NaN,NaN,NaN,NaN,NaN
urban_or_rural,15000,2,Urban,10282,NaN,NaN,NaN,NaN,NaN,NaN,NaN
daily_ai_tool_usage_hrs,15000.0,NaN,NaN,NaN,2.013893,1.735977,0.0,0.4,1.8,3.2,8.0
primary_ai_tools_used,11785,5,ChatGPT,5469,NaN,NaN,NaN,NaN,NaN,NaN,NaN
uses_ai_for_assignments,15000,5,Never,4603,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ai_replaces_own_thinking_score,15000.0,NaN,NaN,NaN,2.987733,1.311932,1.0,2.0,3.0,4.0,5.0
ai_dependency_score,15000.0,NaN,NaN,NaN,4.539133,2.315115,1.0,3.0,4.0,6.0,10.0
placement_anxiety_score,15000.0,NaN,NaN,NaN,5.913933,2.548207,1.0,4.0,6.0,8.0,10.0
fear_of_job_loss_to_ai,15000.0,NaN,NaN,NaN,3.5512,1.180397,1.0,3.0,4.0,5.0,5.0
career_clarity_score,15000.0,NaN,NaN,NaN,5.025333,2.200806,1.0,3.0,5.0,6.0,10.0
internship_experience,15000.0,NaN,NaN,NaN,1.718333,1.069583,0.0,1.0,2.0,2.0,4.0
weekly_job_application_count,15000.0,NaN,NaN,NaN,10.636133,6.402411,0.0,6.0,10.0,15.0,35.0
resume_confidence_score,15000.0,NaN,NaN,NaN,3.298333,1.245352,1.0,2.0,3.0,4.0,5.0
interview_anxiety_score,15000.0,NaN,NaN,NaN,6.108267,2.638448,1.0,4.0,6.0,8.0,10.0
daily_study_hours,15000.0,NaN,NaN,NaN,2.73066,1.801026,0.0,1.3,2.6,4.0,10.3
self_learning_hours_per_week,14767.0,NaN,NaN,NaN,6.304612,5.55388,0.0,1.0,5.5,10.1,31.0
skill_development_courses_taken,15000.0,NaN,NaN,NaN,2.0326,1.8095,0.0,1.0,2.0,3.0,10.0
social_media_hrs_per_day,14790.0,NaN,NaN,NaN,3.006437,1.649033,0.0,1.8,3.0,4.1,8.0
sleep_hours,14797.0,NaN,NaN,NaN,6.993364,1.004809,4.0,6.3,7.0,7.7,10.0
stress_level,15000.0,NaN,NaN,NaN,4.771133,1.77821,1.0,4.0,5.0,6.0,10.0
burnout_score,15000.0,NaN,NaN,NaN,5.4726,2.068317,1.0,4.0,5.0,7.0,10.0
motivation_score,15000.0,NaN,NaN,NaN,4.319733,2.151266,1.0,3.0,4.0,6.0,10.0
seeks_career_counseling,14780.0,NaN,NaN,NaN,0.285792,0.451806,0.0,0.0,0.0,1.0,1.0
overall_career_readiness_score,15000.0,NaN,NaN,NaN,5.998019,1.593982,1.0,4.9,6.0,7.12,10.0

In [98]:
df.info() #Displays a summary of the DataFrame structure.

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 30 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   student_id                       15000 non-null  str
 1   age                              15000 non-null  int64
 2   gender                           15000 non-null  str
 3   degree_type                      15000 non-null  str
 4   stream                           15000 non-null  str
 5   year_of_study                    15000 non-null  int64
 6   college_tier                     15000 non-null  str
 7   urban_or_rural                   15000 non-null  str
 8   daily_ai_tool_usage_hrs          15000 non-null  float64
 9   primary_ai_tools_used            11785 non-null  str
 10  uses_ai_for_assignments          15000 non-null  str
 11  ai_replaces_own_thinking_score   15000 non-null  int64
 12  ai_dependency_score              15000 non-null  int64
 13  placement_anxiety_score          15000 non-null  int64
 14  fear_of_job_loss_to_ai           15000 non-null  int64
 15  career_clarity_score             15000 non-null  int64
 16  internship_experience            15000 non-null  int64
 17  weekly_job_application_count     15000 non-null  int64
 18  resume_confidence_score          15000 non-null  int64
 19  interview_anxiety_score          15000 non-null  int64
 20  daily_study_hours                15000 non-null  float64
 21  self_learning_hours_per_week     14767 non-null  float64
 22  skill_development_courses_taken  15000 non-null  int64
 23  social_media_hrs_per_day         14790 non-null  float64
 24  sleep_hours                      14797 non-null  float64
 25  stress_level                     15000 non-null  int64
 26  burnout_score                    15000 non-null  int64
 27  motivation_score                 15000 non-null  int64
 28  seeks_career_counseling          14780 non-null  float64
 29  overall_career_readiness_score   15000 non-null  float64
dtypes: float64(7), int64(15), str(8)
memory usage: 3.4 MB

In [99]:
df.drop_duplicates(inplace=True) # Remove duplicate rows from the DataFrame df.
print("Number of duplicate rows Now:", df.duplicated().sum()) # After dropping duplicates, check again to confirm that there are no duplicate rows remaining in the DataFrame df.

Number of duplicate rows Now: 0

In [100]:
# ============================================================
# 🗑️ DROP IRRELEVANT COLUMNS
# ============================================================

cols_to_drop = [
    'student_id',        # unique identifier — no predictive power
]

df = df.drop(columns=cols_to_drop, errors='ignore')
print(f"✅ Dropped {len(cols_to_drop)} columns")
print(f"   Remaining columns: {df.shape[1]}")

✅ Dropped 1 columns
   Remaining columns: 29

In [101]:
# ============================================================
# 🧹 COLUMN NAME SANITIZATION
# ============================================================
df.columns = (
    df.columns
    .str.lower()                                        # lowercase everything
    .str.strip()                                        # remove leading/trailing whitespace
    .str.replace(r"[^a-z0-9]+", "_", regex=True)       # replace anything not a letter/number with _
    .str.strip("_")                                     # remove leading/trailing underscores
)

print("✅ Columns sanitized:")
print(df.columns.tolist())

✅ Columns sanitized:
['age', 'gender', 'degree_type', 'stream', 'year_of_study', 'college_tier', 'urban_or_rural', 'daily_ai_tool_usage_hrs', 'primary_ai_tools_used', 'uses_ai_for_assignments', 'ai_replaces_own_thinking_score', 'ai_dependency_score', 'placement_anxiety_score', 'fear_of_job_loss_to_ai', 'career_clarity_score', 'internship_experience', 'weekly_job_application_count', 'resume_confidence_score', 'interview_anxiety_score', 'daily_study_hours', 'self_learning_hours_per_week', 'skill_development_courses_taken', 'social_media_hrs_per_day', 'sleep_hours', 'stress_level', 'burnout_score', 'motivation_score', 'seeks_career_counseling', 'overall_career_readiness_score']

#### 🧠 Create the profiling report

In [102]:
# create the instance of the Sweetviz report
report = sv.analyze(df)

# Save the report as an HTML file
report.show_html("Report_AI_dependency.html")

# Success message
print("✅ Success! The Sweetviz report was created successfully.")
print("📄 Report saved as: Report_AI_dependency.html")

Done! Use 'show' commands to display/save.   |██████████| [100%]   00:01 -> (00:00 left)

Report Report_AI_dependency.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.
✅ Success! The Sweetviz report was created successfully.
📄 Report saved as: Report_AI_dependency.html